"""news

Revision ID: 1904b97596d7
Revises: 3f6b94e050c7
Create Date: 2026-01-23 09:20:23.646890

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1904b97596d7'
down_revision = '3f6b94e050c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
