"""news

Revision ID: 1e07864308b8
Revises: 8e9c0a2bf9b6
Create Date: 2026-01-09 23:24:50.531323

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e07864308b8'
down_revision = '8e9c0a2bf9b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
