"""news

Revision ID: 1f738f64aa0c
Revises: 5518736738ef
Create Date: 2026-01-20 09:57:15.968603

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1f738f64aa0c'
down_revision = '5518736738ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shops', sa.Column('is_frozen', sa.Boolean(), nullable=False))
    op.alter_column('shops', 'wb_token_enc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('session_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_version')
    op.alter_column('shops', 'wb_token_enc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('shops', 'is_frozen')
    op.drop_table('system_flags')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
