"""news

Revision ID: 24a3c65ef23e
Revises: ce2ac94fd888
Create Date: 2026-01-12 00:02:05.723515

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a3c65ef23e'
down_revision = 'ce2ac94fd888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_signatures_is_active'), 'signatures', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_is_active'), table_name='signatures')
    # ### end Alembic commands ###
