"""news

Revision ID: 2cd6e3cda3fd
Revises: 9b0db273568f
Create Date: 2026-01-11 17:39:13.230591

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '2cd6e3cda3fd'
down_revision = '9b0db273568f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_prompt_records_scope_key')
    )
    op.create_index('ix_prompt_records_key', 'prompt_records', ['key'], unique=False)
    op.create_index('ix_prompt_records_scope', 'prompt_records', ['scope'], unique=False)
    op.create_table('shop_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'user_id', name='uq_shop_members_shop_user')
    )
    op.create_index('ix_shop_members_shop_id', 'shop_members', ['shop_id'], unique=False)
    op.create_index('ix_shop_members_user_id', 'shop_members', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index('ix_shop_members_user_id', table_name='shop_members')
    op.drop_index('ix_shop_members_shop_id', table_name='shop_members')
    op.drop_table('shop_members')
    op.drop_index('ix_prompt_records_scope', table_name='prompt_records')
    op.drop_index('ix_prompt_records_key', table_name='prompt_records')
    op.drop_table('prompt_records')
    # ### end Alembic commands ###
