"""news

Revision ID: 3f6b94e050c7
Revises: 
Create Date: 2026-01-23 08:56:51.128919

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3f6b94e050c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('prompt_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_prompt_records_scope_key')
    )
    op.create_index('ix_prompt_records_key', 'prompt_records', ['key'], unique=False)
    op.create_index('ix_prompt_records_scope', 'prompt_records', ['scope'], unique=False)
    op.create_table('system_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tones_code'), 'tones', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('wb_token_enc', sa.Text(), nullable=True),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_owner_user_id'), 'shops', ['owner_user_id'], unique=False)
    op.create_table('chat_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_drafts_chat_id'), 'chat_drafts', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_drafts_shop_id'), 'chat_drafts', ['shop_id'], unique=False)
    op.create_table('chat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('is_new_chat', sa.Boolean(), nullable=False),
    sa.Column('add_timestamp_ms', sa.BigInteger(), nullable=True),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'event_id', name='uq_chat_events_shop_event')
    )
    op.create_index(op.f('ix_chat_events_chat_id'), 'chat_events', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_events_shop_id'), 'chat_events', ['shop_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('reply_sign', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('good_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'chat_id', name='uq_chat_sessions_shop_chat')
    )
    op.create_index(op.f('ix_chat_sessions_shop_id'), 'chat_sessions', ['shop_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('day_utc', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'day_utc', 'metric', name='uq_daily_stats')
    )
    op.create_index(op.f('ix_daily_stats_day_utc'), 'daily_stats', ['day_utc'], unique=False)
    op.create_index(op.f('ix_daily_stats_metric'), 'daily_stats', ['metric'], unique=False)
    op.create_index(op.f('ix_daily_stats_shop_id'), 'daily_stats', ['shop_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('wb_id', sa.String(length=64), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('product_valuation', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('was_viewed', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_state', sa.String(length=32), nullable=True),
    sa.Column('answer_editable', sa.Boolean(), nullable=True),
    sa.Column('product_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'wb_id', name='uq_feedbacks_shop_wb')
    )
    op.create_index(op.f('ix_feedbacks_created_date'), 'feedbacks', ['created_date'], unique=False)
    op.create_index(op.f('ix_feedbacks_shop_id'), 'feedbacks', ['shop_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_name'), 'feedbacks', ['user_name'], unique=False)
    op.create_index(op.f('ix_feedbacks_wb_id'), 'feedbacks', ['wb_id'], unique=False)
    op.create_table('gpt_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('cost_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('response_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpt_usage_created_at'), 'gpt_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_gpt_usage_operation_type'), 'gpt_usage', ['operation_type'], unique=False)
    op.create_index(op.f('ix_gpt_usage_shop_id'), 'gpt_usage', ['shop_id'], unique=False)
    op.create_table('hourly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('bucket_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'bucket_utc', 'metric', name='uq_hourly_stats')
    )
    op.create_index(op.f('ix_hourly_stats_bucket_utc'), 'hourly_stats', ['bucket_utc'], unique=False)
    op.create_index(op.f('ix_hourly_stats_metric'), 'hourly_stats', ['metric'], unique=False)
    op.create_index(op.f('ix_hourly_stats_shop_id'), 'hourly_stats', ['shop_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_shop_id'), 'payments', ['shop_id'], unique=False)
    op.create_table('product_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_code', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_name', sa.String(length=160), nullable=True),
    sa.Column('thumb_url', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wb_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'nm_id', name='uq_product_cards_shop_nm')
    )
    op.create_index(op.f('ix_product_cards_nm_id'), 'product_cards', ['nm_id'], unique=False)
    op.create_index(op.f('ix_product_cards_shop_id'), 'product_cards', ['shop_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('wb_id', sa.String(length=64), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('was_viewed', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_editable', sa.Boolean(), nullable=True),
    sa.Column('product_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'wb_id', name='uq_questions_shop_wb')
    )
    op.create_index(op.f('ix_questions_created_date'), 'questions', ['created_date'], unique=False)
    op.create_index(op.f('ix_questions_shop_id'), 'questions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_questions_user_name'), 'questions', ['user_name'], unique=False)
    op.create_index(op.f('ix_questions_wb_id'), 'questions', ['wb_id'], unique=False)
    op.create_table('shop_credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_credit_ledger_actor_user_id'), 'shop_credit_ledger', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_shop_credit_ledger_shop_id'), 'shop_credit_ledger', ['shop_id'], unique=False)
    op.create_table('shop_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'user_id', name='uq_shop_members_shop_user')
    )
    op.create_index('ix_shop_members_shop_id', 'shop_members', ['shop_id'], unique=False)
    op.create_index('ix_shop_members_user_id', 'shop_members', ['user_id'], unique=False)
    op.create_table('shop_settings',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('reply_mode', sa.String(length=16), nullable=False),
    sa.Column('auto_draft', sa.Boolean(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('auto_draft_limit_per_sync', sa.Integer(), nullable=False),
    sa.Column('rating_mode_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_rating_to_autopublish', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('tone', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=120), nullable=True),
    sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blacklist_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whitelist_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions_reply_mode', sa.String(length=16), nullable=False),
    sa.Column('questions_auto_draft', sa.Boolean(), nullable=False),
    sa.Column('questions_auto_publish', sa.Boolean(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('chat_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_feedback_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_questions_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_chat_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chat_next_ms', sa.Integer(), nullable=True),
    sa.Column('last_cards_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cards_cursor_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cards_cursor_nm_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_brand'), 'signatures', ['brand'], unique=False)
    op.create_index(op.f('ix_signatures_is_active'), 'signatures', ['is_active'], unique=False)
    op.create_index(op.f('ix_signatures_shop_id'), 'signatures', ['shop_id'], unique=False)
    op.create_index(op.f('ix_signatures_type'), 'signatures', ['type'], unique=False)
    op.create_table('feedback_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_drafts_feedback_id'), 'feedback_drafts', ['feedback_id'], unique=False)
    op.create_table('question_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_drafts_question_id'), 'question_drafts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_drafts_question_id'), table_name='question_drafts')
    op.drop_table('question_drafts')
    op.drop_index(op.f('ix_feedback_drafts_feedback_id'), table_name='feedback_drafts')
    op.drop_table('feedback_drafts')
    op.drop_index(op.f('ix_signatures_type'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_shop_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_is_active'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_brand'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_table('shop_settings')
    op.drop_index('ix_shop_members_user_id', table_name='shop_members')
    op.drop_index('ix_shop_members_shop_id', table_name='shop_members')
    op.drop_table('shop_members')
    op.drop_index(op.f('ix_shop_credit_ledger_shop_id'), table_name='shop_credit_ledger')
    op.drop_index(op.f('ix_shop_credit_ledger_actor_user_id'), table_name='shop_credit_ledger')
    op.drop_table('shop_credit_ledger')
    op.drop_index(op.f('ix_questions_wb_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_user_name'), table_name='questions')
    op.drop_index(op.f('ix_questions_shop_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_date'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_product_cards_shop_id'), table_name='product_cards')
    op.drop_index(op.f('ix_product_cards_nm_id'), table_name='product_cards')
    op.drop_table('product_cards')
    op.drop_index(op.f('ix_payments_shop_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_hourly_stats_shop_id'), table_name='hourly_stats')
    op.drop_index(op.f('ix_hourly_stats_metric'), table_name='hourly_stats')
    op.drop_index(op.f('ix_hourly_stats_bucket_utc'), table_name='hourly_stats')
    op.drop_table('hourly_stats')
    op.drop_index(op.f('ix_gpt_usage_shop_id'), table_name='gpt_usage')
    op.drop_index(op.f('ix_gpt_usage_operation_type'), table_name='gpt_usage')
    op.drop_index(op.f('ix_gpt_usage_created_at'), table_name='gpt_usage')
    op.drop_table('gpt_usage')
    op.drop_index(op.f('ix_feedbacks_wb_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_user_name'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_shop_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_created_date'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_daily_stats_shop_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_metric'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_day_utc'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_chat_sessions_shop_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_events_shop_id'), table_name='chat_events')
    op.drop_index(op.f('ix_chat_events_chat_id'), table_name='chat_events')
    op.drop_table('chat_events')
    op.drop_index(op.f('ix_chat_drafts_shop_id'), table_name='chat_drafts')
    op.drop_index(op.f('ix_chat_drafts_chat_id'), table_name='chat_drafts')
    op.drop_table('chat_drafts')
    op.drop_index(op.f('ix_shops_owner_user_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tones_code'), table_name='tones')
    op.drop_table('tones')
    op.drop_table('system_flags')
    op.drop_index('ix_prompt_records_scope', table_name='prompt_records')
    op.drop_index('ix_prompt_records_key', table_name='prompt_records')
    op.drop_table('prompt_records')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
