"""news

Revision ID: 48f9d457b7d0
Revises: 2cd6e3cda3fd
Create Date: 2026-01-11 19:27:36.447463

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f9d457b7d0'
down_revision = '2cd6e3cda3fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tones_code'), 'tones', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tones_code'), table_name='tones')
    op.drop_table('tones')
    # ### end Alembic commands ###
