"""add_last_full_sync_at

Revision ID: 720162cfc282
Revises: 5636f67a3eaa
Create Date: 2026-02-02 23:07:55.589720

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720162cfc282'
down_revision = '5636f67a3eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_settings', sa.Column('last_full_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'last_full_sync_at')
    # ### end Alembic commands ###
