"""news

Revision ID: 8e9c0a2bf9b6
Revises: 38349fd519cc
Create Date: 2026-01-09 22:46:01.099946

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e9c0a2bf9b6'
down_revision = '38349fd519cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_code', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_name', sa.String(length=160), nullable=True),
    sa.Column('thumb_url', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wb_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'nm_id', name='uq_product_cards_shop_nm')
    )
    op.create_index(op.f('ix_product_cards_nm_id'), 'product_cards', ['nm_id'], unique=False)
    op.create_index(op.f('ix_product_cards_shop_id'), 'product_cards', ['shop_id'], unique=False)
    op.add_column('shop_settings', sa.Column('last_cards_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shop_settings', sa.Column('cards_cursor_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shop_settings', sa.Column('cards_cursor_nm_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'cards_cursor_nm_id')
    op.drop_column('shop_settings', 'cards_cursor_updated_at')
    op.drop_column('shop_settings', 'last_cards_sync_at')
    op.drop_index(op.f('ix_product_cards_shop_id'), table_name='product_cards')
    op.drop_index(op.f('ix_product_cards_nm_id'), table_name='product_cards')
    op.drop_table('product_cards')
    # ### end Alembic commands ###
