"""news

Revision ID: 909e268179ad
Revises: 
Create Date: 2026-01-09 01:00:21.929683

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '909e268179ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('wb_token_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_owner_user_id'), 'shops', ['owner_user_id'], unique=False)
    op.create_table('chat_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_drafts_chat_id'), 'chat_drafts', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_drafts_shop_id'), 'chat_drafts', ['shop_id'], unique=False)
    op.create_table('chat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('is_new_chat', sa.Boolean(), nullable=False),
    sa.Column('add_timestamp_ms', sa.BigInteger(), nullable=True),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'event_id', name='uq_chat_events_shop_event')
    )
    op.create_index(op.f('ix_chat_events_chat_id'), 'chat_events', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_events_shop_id'), 'chat_events', ['shop_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('reply_sign', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('good_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'chat_id', name='uq_chat_sessions_shop_chat')
    )
    op.create_index(op.f('ix_chat_sessions_shop_id'), 'chat_sessions', ['shop_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('wb_id', sa.String(length=64), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('product_valuation', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('was_viewed', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_state', sa.String(length=32), nullable=True),
    sa.Column('answer_editable', sa.Boolean(), nullable=True),
    sa.Column('product_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'wb_id', name='uq_feedbacks_shop_wb')
    )
    op.create_index(op.f('ix_feedbacks_created_date'), 'feedbacks', ['created_date'], unique=False)
    op.create_index(op.f('ix_feedbacks_shop_id'), 'feedbacks', ['shop_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_name'), 'feedbacks', ['user_name'], unique=False)
    op.create_index(op.f('ix_feedbacks_wb_id'), 'feedbacks', ['wb_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('wb_id', sa.String(length=64), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('was_viewed', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_editable', sa.Boolean(), nullable=True),
    sa.Column('product_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'wb_id', name='uq_questions_shop_wb')
    )
    op.create_index(op.f('ix_questions_created_date'), 'questions', ['created_date'], unique=False)
    op.create_index(op.f('ix_questions_shop_id'), 'questions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_questions_user_name'), 'questions', ['user_name'], unique=False)
    op.create_index(op.f('ix_questions_wb_id'), 'questions', ['wb_id'], unique=False)
    op.create_table('shop_settings',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('reply_mode', sa.String(length=16), nullable=False),
    sa.Column('auto_draft', sa.Boolean(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('rating_mode_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_rating_to_autopublish', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('tone', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=120), nullable=True),
    sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blacklist_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whitelist_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions_reply_mode', sa.String(length=16), nullable=False),
    sa.Column('questions_auto_draft', sa.Boolean(), nullable=False),
    sa.Column('questions_auto_publish', sa.Boolean(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('chat_auto_reply', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_questions_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_chat_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chat_next_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('feedback_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_drafts_feedback_id'), 'feedback_drafts', ['feedback_id'], unique=False)
    op.create_table('question_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=True),
    sa.Column('openai_response_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_drafts_question_id'), 'question_drafts', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_drafts_question_id'), table_name='question_drafts')
    op.drop_table('question_drafts')
    op.drop_index(op.f('ix_feedback_drafts_feedback_id'), table_name='feedback_drafts')
    op.drop_table('feedback_drafts')
    op.drop_table('shop_settings')
    op.drop_index(op.f('ix_questions_wb_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_user_name'), table_name='questions')
    op.drop_index(op.f('ix_questions_shop_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_date'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_feedbacks_wb_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_user_name'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_shop_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_created_date'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_chat_sessions_shop_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_events_shop_id'), table_name='chat_events')
    op.drop_index(op.f('ix_chat_events_chat_id'), table_name='chat_events')
    op.drop_table('chat_events')
    op.drop_index(op.f('ix_chat_drafts_shop_id'), table_name='chat_drafts')
    op.drop_index(op.f('ix_chat_drafts_chat_id'), table_name='chat_drafts')
    op.drop_table('chat_drafts')
    op.drop_index(op.f('ix_shops_owner_user_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
