"""news

Revision ID: ce2ac94fd888
Revises: 48f9d457b7d0
Create Date: 2026-01-11 23:33:39.420224

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2ac94fd888'
down_revision = '48f9d457b7d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_brand'), 'signatures', ['brand'], unique=False)
    op.create_index(op.f('ix_signatures_shop_id'), 'signatures', ['shop_id'], unique=False)
    op.create_index(op.f('ix_signatures_type'), 'signatures', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_type'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_shop_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_brand'), table_name='signatures')
    op.drop_table('signatures')
    # ### end Alembic commands ###
